db:
  image: mysql
  ports:
    - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=adminpassword
    - MYSQL_DATABASE=chatchat
  container_name: chat-mysql